name: subnetwork_inference-env
dependencies:
    - python=3.7
    - numpy=1.17.2
    - matplotlib=3.1.2
    - seaborn=0.10.0
    - pytorch
    - torchvision
    - cudatoolkit=9.2
    - tqdm
    - pip=20.0.2
    - Pillow=6.1
    - opt_einsum
    - pip:
        - backpack-for-pytorch
